### ISSUE TITLE
Can't reproduce results mentioned on the paper.

### ISSUE THREAD

**Issue by amblee0306** [ljxw88/deephgcn#1]
Hi there, was looking at your paper and tried to reproduce the results but can't seem to do so especially for citeseer for nc task. On the side note, the lp task can't be run. I didn't change the code. Just ran ```python run_citeseer.py``` and only got a score of 59.5.

**Comment by ljxw88** [comment]
<img width="689" alt="image" src="https://github.com/user-attachments/assets/6fcc92e5-83f2-4a32-bb01-3274954185f7">

Hi, I have updated the code and resolved the issue on citeseer parameter setting. Thanks for raising the issue. Now it should be resoved and I can obtain the result as shown in the figure.

**Comment by ljxw88** [comment]
Airport
<img width="677" alt="image" src="https://github.com/user-attachments/assets/5f6421fc-9cfd-4a1e-b77d-3fa88dc7c1de">

Cora
<img width="675" alt="image" src="https://github.com/user-attachments/assets/63e1c5d5-dbde-4cbb-9efc-4bd70be4f7e1">

Pubmed
<img width="679" alt="image" src="https://github.com/user-attachments/assets/30640047-3384-4c6d-962d-47ce29b0e6bd">

Here are some following up results on Airport, Cora and Pubmed datasets. These results can be reproduced via the updated scripts in this repo. The produced results on Airport and Pubmed are substantially higher than the reported results in the paper.
